# This workflow will publish docfx documentation at githubpaages
# This code was taken from docfx documentation: https://dotnet.github.io/docfx/index.html

name: docfx

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
    - main
    
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Chekout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet tool update -g docfx
    - run: docfx Realtime-ToDo-Web-API.Documentation/docfx.json

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'Realtime-ToDo-Web-API.Documentation/_site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
