# This workflow will publish docfx documentation at githubpaages
# This code was taken from docfx documentation: https://dotnet.github.io/docfx/index.html

name: docfx

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
    - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    environment:
      name: 'Documentation'
      url: https://ponatosik.github.io/Realtime-ToDo-Web-API/
    steps:
    - name: Chekout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet tool update -g docfx
    - run: docfx Realtime-ToDo-Web-API.Documentation/docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
